# Generated by Django 3.1.2 on 2020-12-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='QDDK5P6VQON1VUFBNLFN', max_length=20),
        ),
    ]
