# Generated by Django 3.1.2 on 2020-12-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0003_auto_20201211_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='E9BIF4AZ4PR2SVKORCPH', max_length=20),
        ),
    ]
