# Generated by Django 3.1.2 on 2020-12-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0004_auto_20201211_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='2MLX6JEZH7732E3DBSA1', max_length=20),
        ),
    ]
