# Generated by Django 3.1.2 on 2020-12-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0005_auto_20201213_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='IEO0WDLNIU4MPDQEOKD4', max_length=20),
        ),
    ]
