# Generated by Django 3.1.2 on 2020-12-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0006_auto_20201213_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='DGMJI2LUIW1MVT80OL8W', max_length=20),
        ),
    ]
