# Generated by Django 3.1.2 on 2020-12-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0007_auto_20201215_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='HW0EDDCDUOYXGL9YO3DM', max_length=20),
        ),
    ]
