# Generated by Django 3.1.2 on 2020-12-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0009_auto_20201215_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='UKEDRHUV9G4RIDV2CYSP', max_length=20),
        ),
    ]
