# Generated by Django 3.1.2 on 2020-12-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0010_auto_20201215_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='IUE567JOHLXEP6C0NIWV', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientMobile1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
