# Generated by Django 3.1.2 on 2020-12-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0012_auto_20201219_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='CountBalces',
        ),
        migrations.AlterField(
            model_name='item',
            name='BalcesNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='T6NM4U1HFND53B49XU69', max_length=20),
        ),
    ]
