# Generated by Django 3.1.2 on 2021-01-07 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0013_auto_20201221_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballses',
            name='Patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.patient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='E49RH8OKYPUBBUKZ66JW', max_length=20),
        ),
    ]
