# Generated by Django 3.1.2 on 2021-01-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0016_auto_20210107_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='BE009ZV432HGB7BMNKHX', max_length=20),
        ),
    ]
