# Generated by Django 3.1.2 on 2021-01-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0017_auto_20210107_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='WO1BVL3FOGRWTOG7JXNY', max_length=20),
        ),
    ]
