# Generated by Django 3.1.2 on 2020-10-25 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_entry_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.names'),
        ),
    ]
