# Generated by Django 3.1.2 on 2020-12-11 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novav1', '0003_auto_20201211_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrudUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('allDay', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('backgroundColor', models.CharField(blank=True, max_length=50, null=True)),
                ('borderColor', models.CharField(blank=True, max_length=50, null=True)),
                ('event_note', models.TextField(blank=True, null=True)),
                ('arrive', models.BooleanField(default=False)),
                ('arrivetime', models.DateTimeField(blank=True, null=True)),
                ('arrivetime2', models.DateTimeField(auto_now_add=True, null=True)),
                ('start', models.BooleanField(default=False)),
                ('start_session', models.DateTimeField(blank=True, null=True)),
                ('end', models.BooleanField(default=False)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('session_used_balls', models.IntegerField(blank=True, null=True)),
                ('branch_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_event', to='novav1.branch')),
                ('event_area', models.ManyToManyField(blank=True, null=True, to='novav1.pricing')),
                ('event_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_doctor', to='novav1.doctorin')),
                ('event_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.patient')),
                ('event_type', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_manage.eventtype')),
                ('session_area', models.ManyToManyField(blank=True, null=True, related_name='session_area', to='novav1.pricing')),
                ('session_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_branch', to='novav1.branch')),
                ('session_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_clinic', to='novav1.clinc')),
                ('session_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_doctor', to='novav1.doctorin')),
            ],
        ),
        migrations.CreateModel(
            name='deviceparameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('CandelaAlex', models.BooleanField()),
                ('DekaAlex', models.BooleanField()),
                ('DekaMoveo', models.BooleanField()),
                ('Joule', models.IntegerField()),
                ('msec', models.IntegerField()),
                ('PulseCount', models.IntegerField()),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Area_Name', to='novav1.pricing')),
                ('OperatorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Operator_Name', to='novav1.doctorin')),
                ('Patient_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.patient')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_manage.events')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.pricing')),
            ],
        ),
    ]
