# Generated by Django 3.1.2 on 2020-12-13 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0006_auto_20201213_2203'),
        ('event_manage', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='branch_event',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_event', to='novav1.branch'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_area',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, to='novav1.pricing'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_doctor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_doctor', to='novav1.doctorin'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.patient'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_manage.eventtype'),
        ),
        migrations.AlterField(
            model_name='events',
            name='session_area',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, related_name='session_area', to='novav1.pricing'),
        ),
        migrations.AlterField(
            model_name='events',
            name='session_branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_branch', to='novav1.branch'),
        ),
        migrations.AlterField(
            model_name='events',
            name='session_clinic',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_clinic', to='novav1.clinc'),
        ),
        migrations.AlterField(
            model_name='events',
            name='session_doctor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_doctor', to='novav1.doctorin'),
        ),
    ]
