# Generated by Django 3.1.2 on 2020-12-15 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0007_auto_20201215_1159'),
        ('event_manage', '0003_auto_20201213_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_Category', to='novav1.category'),
        ),
    ]
