# Generated by Django 3.1.2 on 2020-12-15 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0008_auto_20201215_1203'),
        ('event_manage', '0004_events_event_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_clinic',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_clinic', to='novav1.clinc'),
        ),
    ]
