# Generated by Django 3.1.2 on 2020-12-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manage', '0005_events_event_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceparameters',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='deviceparameters',
            name='event',
        ),
    ]
