# Generated by Django 3.1.2 on 2020-12-15 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0010_auto_20201215_1924'),
        ('event_manage', '0006_auto_20201215_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceparameters',
            name='Patient_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.patient'),
        ),
        migrations.AlterField(
            model_name='deviceparameters',
            name='part',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.pricing'),
        ),
    ]
