# Generated by Django 3.1.2 on 2020-12-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manage', '0007_auto_20201215_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceparameters',
            name='CandelaAlex',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deviceparameters',
            name='DekaAlex',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deviceparameters',
            name='DekaMoveo',
            field=models.BooleanField(default=True),
        ),
    ]
