# Generated by Django 3.1.2 on 2020-12-11 07:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novav1', '0004_auto_20201211_0951'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='statue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statue', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.TextField(max_length=100)),
                ('Calldate', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('Followup', models.IntegerField(blank=True, choices=[(1, '1 day'), (2, '2days'), (3, '3days'), (4, '4days'), (5, '5days'), (6, '6days'), (7, 'week'), (14, 'weeks'), (30, 'Month')], null=True)),
                ('FollowupIN', models.DateField(blank=True, null=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novav1.patient')),
                ('Statue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.statue')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
