# Generated by Django 3.1.2 on 2021-01-07 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0014_auto_20210107_1013'),
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.patient'),
        ),
    ]
